micronaut:
  application:
    name: keyManagerGrpc

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/pix`}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}
    driverClassName: ${JDBC_DRIVER:`org.postgresql.Driver`}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

apis:
  itau:
    erp:
      url: ${$ERP_API:`http://localhost:9091/api/v1/clientes`}
  bancocentral:
    url: ${$BCB_API:`http://localhost:8082/api/v1/pix`}
